# -*- coding: utf-8 -*-
"""Cópia de rag_huggingface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waSvB0Ccayaos0gjQvr7LjBo1mPoU4Lh
"""

!pip install transformers sentence-transformers faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from transformers import pipeline

# Base de conhecimento
documents = [
    "Hugging Face é uma plataforma de inteligência artificial.",
    "RAG combina recuperação de informação com geração de texto.",
    "Modelos de linguagem podem responder perguntas com contexto."
]

# Criar embeddings
embedder = SentenceTransformer('all-MiniLM-L6-v2')
doc_embeddings = embedder.encode(documents)

# Criar índice vetorial
dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(doc_embeddings))

# Função de busca
def retrieve(query):
    query_embedding = embedder.encode([query])
    D, I = index.search(np.array(query_embedding), k=2)
    return [documents[i] for i in I[0]]

# Modelo gerador
generator = pipeline("text-generation", model="gpt2")

# Pergunta
query = "O que é RAG?"

# Recuperar contexto
context = retrieve(query)

# Gerar resposta
prompt = f"Contexto: {context}\nPergunta: {query}\nResposta:"
response = generator(prompt, max_length=100)

print(response[0]['generated_text'])